heat_template_version: 2014-10-16
parameters:
  ComputeKernelArgs:
    default: "default_hugepagesz=1GB hugepagesz=1G hugepages=512 iommu=pt intel_iommu=on"
    type: string

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: swapon_config}
      - config: {get_resource: firstboot_config}
      - config: {get_resource: compute_R730_kernel_args}

  swapon_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        swap_device=$(sudo fdisk -l | grep swap | awk '{print $1}')
        if [[ $swap_device && ${swap_device} ]]; then
          rc_local="/etc/rc.d/rc.local"
          echo "swapon $swap_device " >> $rc_local
          chmod 755 $rc_local
          swapon $swap_device
        fi

  firstboot_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: /home/stack/templates/firstboot/firstboot-setup.sh}
           
  compute_R730_kernel_args:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            FORMAT="compute"
            if [[ $(hostname) == *$FORMAT* ]] ; then
              TUNED_CORES='4,6,8,10,12,14,16,18,20,22,24,26,1,3,5,7,9,11,13,15,17,19,21,23,25,27,32,34,36,38,40,42,44,46,48,50,52,54,29,31,33,35,37,39,41,43,45,47,49,51,53,55'
              sed 's/^\(GRUB_CMDLINE_LINUX=".*\)"/\1 $KERNEL_ARGS isolcpus=$TUNED_CORES"/g' -i /etc/default/grub ;
              grub2-mkconfig -o /etc/grub2.cfg
              reboot
            fi
          params:
            $KERNEL_ARGS: {get_param: ComputeKernelArgs}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
